language: go

sudo: false

os:
  - osx
  - linux
  - windows

go:
  - 1.11.x
  - 1.12.x

before_install:
  - go get -u golang.org/x/lint/golint

script:
  - golint -set_exit_status buffer colors config ds formatters levels names pool printer .
  - go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)
