name: Lint and Test with Coverage
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.12
      uses: actions/setup-go@v1
      with:
        go-version: 1.12
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Lint and Test
      run: |
        export GOBIN=$(go env GOROOT)/bin
        export PATH=$PATH:$GOBIN
        GO111MODULE=off go get -u golang.org/x/lint/golint
        go install golang.org/x/lint/golint
        make check
    
    - name: Send coverage
      run: bash <(curl -s https://codecov.io/bash)
